"""initial_canonical_schema

Revision ID: 4da34d9fddb2
Revises: 
Create Date: 2026-09-20 00:57:24.801593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da34d9fddb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodities', schema=None) as batch_op:
        batch_op.alter_column('initial_moisture_pct',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('critical_moisture_pct',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(15.0)'))
        batch_op.alter_column('water_activity_aw',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.7)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodities', schema=None) as batch_op:
        batch_op.alter_column('water_activity_aw',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.7)'))
        batch_op.alter_column('critical_moisture_pct',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(15.0)'))
        batch_op.alter_column('initial_moisture_pct',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(50.0)'))

    # ### end Alembic commands ###
